apiVersion: apps/v1
kind: Deployment
metadata:
  name: fre-app-deployment
  labels:
    app: fre-app-dep
  namespace: challenge-app-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fre-app
  template:
    metadata:
      labels:
        app: fre-app
    spec:
      containers:
      - name: container-0
        image: curdanetp/fre-app:latest
        resources:
            requests:
                memory: "32Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BE_HOST
          value: "kmaster.mshome.net"
        - name: REACT_APP_BE_PORT
          value: "30004"