apiVersion: v1
kind: Service
metadata:
  name: fre-app-nodeport
  annotations:
    field.cattle.io/description: FrontEnd App Service
  namespace: challenge-app-development
spec:
  selector:
    app: fre-app
  type: NodePort
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 80
    