apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    field.cattle.io/description: FrontEnd App Horizontal Pod Autoscaller
  name: fre-app-hpa
  namespace: challenge-app-development
spec:
  minReplicas: 3
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fre-app-deployment
  metrics:
  - resource:
      name: cpu
      target:
        averageValue: 300m
        type: AverageValue
    type: Resource
  - resource:
      name: memory
      target:
        averageValue: 96Mi
        type: AverageValue
    type: Resource